### ISSUE TITLE
Avoid lock-outs due to enforced 2FA

### ISSUE THREAD

**Issue by tflidd** [ChristophWurst/twofactor_admin#27]
I managed to lock myself out after an update, because the 2FA-provider I was using on my admin account was not enabled after the update. Unfortunately, the whole procedure was very misleading, it said that I don't have 2FA enabled. However, it was enabled before the update, so I was a bit confused.

It would be great that this feature is a bit more user friendly, e.g.:

- a user without 2FA logs in, it just helps to configure a 2FA method right away
- if configured 2FA method for an admin is not available (as well as for all other admins), let the admin login anyway to get the Nextcloud running again. Or use a verification via mail.
- if you enforce 2FA, make sure the admin account already uses 2FA, if not this happens https://help.nextcloud.com/t/i-locked-myself-out/46170
- don't enforce 2FA after an update, if not all 2FA providers are available that were before

**Comment by ChristophWurst** [comment]
Thank you for this feedback. This should be reported in individual tickets in the server repository.

>  a user without 2FA logs in, it just helps to configure a 2FA method right away

This is already being tracked in https://github.com/nextcloud/server/issues/12268

>  if configured 2FA method for an admin is not available (as well as for all other admins), let the admin login anyway to get the Nextcloud running again. Or use a verification via mail.

This would just open doors for attackers. Even if any 2FA providers should not be available because of a missing compatible version, you can always use your backup codes. I would strongly advice against adding such a "feature".



> if you enforce 2FA, make sure the admin account already uses 2FA, if not this happens https://help.nextcloud.com/t/i-locked-myself-out/46170

This is being tracked in https://github.com/nextcloud/server/issues/12267 and someone is working on it at https://github.com/nextcloud/server/pull/13735.

>  don't enforce 2FA after an update, if not all 2FA providers are available that were before

How could this ever be secure? Nextcloud now even tells you if all enabled apps have an update ready before the upgrade. If an admins still decides to upgrade I don't feel like it's *our* fault that there will be issues with 2FA. Please note that we have to always enforce 2FA if a provider has been enabled for a user. This prevents unauthorized logins in the case of a provider failure (be it a bug or attacker triggering that).

**Comment by ChristophWurst** [comment]
Please let me know if anything is still unclear. I would close the ticket otherwise as we have the other server tickets that track the individual issues ;)

**Comment by tflidd** [comment]
> This would just open doors for attackers. Even if any 2FA providers should not be available because of a missing compatible version, you can always use your backup codes. I would strongly advice against adding such a "feature".

the attacker however would need to disable 2FA apps. In that case, there should be a warning before running a upgrade if the admin has not set up backup codes.

For the rest it is ok with me to close this issue. I wasn't sure if these issues are tracked on the server-repo.

**Comment by ChristophWurst** [comment]
That is exactly the point. An attacker might actually be able to trigger disabling of the app either by a bug (Nextcloud disables apps that cause critical errors) or through some other hole (attacker is able to control app management). Then they could log in.

We already have the ability to recover an account from the CLI. And as a last resort there are ways to fix this through changing a few flags in the database. But 99% of the admins should never run into this because they don't upgrade if apps are missing and they have backup codes generated.

**Comment by tflidd** [comment]
I see the problem of being too user friendly and increasing the attack surface. Then, let's close this here. I'll let you know when I have new ideas ;-)

**Comment by ChristophWurst** [comment]
hehe sure!
