### ISSUE TITLE
Problem with id auto_increment

### ISSUE THREAD

**Issue by klipa01** [ChristophWurst/twofactor_admin#79]
Hi,

I use Nextcloud 16.0.5 with the app twofactor_admin version 0.4.1.

I noticed that after setting keys for multiple accounts a single use of such a key leads to a deletion of all datasets in the "table oc_twofactor_admimn_codes". Furthermore all entries in the table contain the value "0" in the field "id" (which will only work if the mysql runs with applicable strict_mode parameters). So I guess, that the expected auto_increment doesn't work for this field as it should (see the relevant migration files in the app folder of twofactor_admin).

After applying "ALTER TABLE NAME_OF_NEXTCLOUD-DB.oc_twofactor_admin_codes CHANGE id id BIGINT(20) UNSIGNED AUTO_INCREMENT;" all worked as expected.

Regards,
Josef

**Comment by HigH-HawK** [comment]
This is probably due to #44 - In previous version, the field `id` had no DEFAULT value, which was causing the plugin to throw errors upon trying to generate one time codes.

@ChristophWurst since the auto_increment grows depending on how often a one time code is being generated and since the fields `id` and `user_id` are PRIMARY fields, would it not be better, to remove the field `id` completely and only work with the field `user_id`?

There should never be more than one one time code per user anyway, so it should be safe to only work with the field `user_id`.

**Comment by ChristophWurst** [comment]
In theory, yes. But the DB abstraction in Nextcloud currently assumes that there is always an int `id`. We're working on this limitation at https://github.com/nextcloud/server/pull/16944, but right now we have to use the `id` column and restrict everything else via a unique constraint.

**Comment by HigH-HawK** [comment]
Ok, so the best method would be to implement an auto_increment for now to fix the problem @klipa01 is having.
